name: Renovate
on:
  schedule:
    - cron: "*/5 * * * *"
  push:
    branches:
      - master
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v29.13.4
        with:
          configurationFile: renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}
